package com.cws.image

enum class Actions {
  SET_IS_INSTRUCTIONS_DIR_READABLE,
  REFRESH_INSTRUCTIONS,
  SET_INSTRUCTIONS_AND_LANGUAGES,
  SET_ACTIVITY,
  CLEAR_ACTIVITY,
  SHOW_CURRENT_VIEW,
  NAVIGATE_TO,
  NAVIGATE_BACK,
  SET_LANGUAGE,
  SET_INSTRUCTION,
  PLAY_INSTRUCTION
}


