package com.cws.image

import com.github.andrewoma.dexx.kollection.*

data class Instruction(val subject: String,
                       val language: String,
                       val path: String,
                       val cueTiming: Int)

data class InstructionIdent(val subject: String, val language: String)

fun ident(instruction: Instruction): InstructionIdent {
  return InstructionIdent(subject = instruction.subject, language = instruction.language)
}

data class State(val canReadInstructionsFiles: Boolean,
                 val canReadInstructionsFilesMessage: String,
                 val languages: ImmutableSet<String>,
                 val language: String,
                 val instructions: ImmutableSet<InstructionIdent>,
                 val instructionsBySubjectLanguagePair: ImmutableMap<InstructionIdent, Instruction>,
                 val navigationStack: NavigationStack)

// Dummy data I started with
val languages = immutableListOf("english",
                                "spanish",
                                "tagalog",
                                "french",
                                "german",
                                "russian",
                                "ethiopian")

val instructions =
    immutableListOf(
        InstructionIdent("chest", "english"),
        InstructionIdent("leg", "english"),
        InstructionIdent("arm", "english"),
        InstructionIdent("chest", "spanish"),
        InstructionIdent("leg", "spanish"),
        InstructionIdent("arm", "spanish"),
        InstructionIdent("chest", "tagalog"),
        InstructionIdent("leg", "tagalog"),
        InstructionIdent("arm", "tagalog"),
        InstructionIdent("chest", "french"),
        InstructionIdent("leg", "french"),
        InstructionIdent("arm", "french"),
        InstructionIdent("chest", "german"),
        InstructionIdent("leg", "german"),
        InstructionIdent("arm", "german"),
        InstructionIdent("chest", "russian"),
        InstructionIdent("leg", "russian"),
        InstructionIdent("arm", "russian"),
        InstructionIdent("chest", "ethiopian"),
        InstructionIdent("leg", "ethiopian"),
        InstructionIdent("arm", "ethiopian")
    )

val instructionsBySubjectLanguagePair =
    immutableMapOf(
        Pair(InstructionIdent("chest", "english"),
             Instruction(subject = "chest",
                         language = "english",
                         path = "chest/english/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "english"),
             Instruction(subject = "leg",
                         language = "english",
                         path = "leg/english/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "english"),
             Instruction(subject = "arm",
                         language = "english",
                         path = "arm/english/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "spanish"),
             Instruction(subject = "chest",
                         language = "spanish",
                         path = "chest/spanish/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "spanish"),
             Instruction(subject = "leg",
                         language = "spanish",
                         path = "leg/spanish/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "spanish"),
             Instruction(subject = "arm",
                         language = "spanish",
                         path = "arm/spanish/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "tagalog"),
             Instruction(subject = "chest",
                         language = "tagalog",
                         path = "chest/tagalog/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "tagalog"),
             Instruction(subject = "leg",
                         language = "tagalog",
                         path = "leg/tagalog/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "tagalog"),
             Instruction(subject = "arm",
                         language = "tagalog",
                         path = "arm/tagalog/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "french"),
             Instruction(subject = "chest",
                         language = "french",
                         path = "chest/french/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "french"),
             Instruction(subject = "leg",
                         language = "french",
                         path = "leg/french/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "french"),
             Instruction(subject = "arm",
                         language = "french",
                         path = "arm/french/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "german"),
             Instruction(subject = "chest",
                         language = "german",
                         path = "chest/german/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "german"),
             Instruction(subject = "leg",
                         language = "german",
                         path = "leg/german/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "german"),
             Instruction(subject = "arm",
                         language = "german",
                         path = "arm/german/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "russian"),
             Instruction(subject = "chest",
                         language = "russian",
                         path = "chest/russian/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "russian"),
             Instruction(subject = "leg",
                         language = "russian",
                         path = "leg/russian/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "russian"),
             Instruction(subject = "arm",
                         language = "russian",
                         path = "arm/russian/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("chest", "ethiopian"),
             Instruction(subject = "chest",
                         language = "ethiopian",
                         path = "chest/ethiopian/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("leg", "ethiopian"),
             Instruction(subject = "leg",
                         language = "ethiopian",
                         path = "leg/ethiopian/path",
                         cueTiming = 1000)),
        Pair(InstructionIdent("arm", "ethiopian"),
             Instruction(subject = "arm",
                         language = "ethiopian",
                         path = "arm/ethiopian/path",
                         cueTiming = 1000))
    )
